name: "Hello Action World"
description: "Une action simple pour GitHub"
author: "ludercej"
inputs:
  name:
    description: "Nom de l'utilisateur"
    required: true
    default: "World"
runs:
  using: "node20"
  main: "index.js"
branding:
  icon: "message-square"
  color: "red"
